/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1bases2;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author carlosmonterroso
 */
public class ConsultaSaldo extends javax.swing.JFrame {
	
	ResultSet datosCuenta;

	/**
	 * Creates new form ConsultaSaldo
	 */
	public ConsultaSaldo() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CajaCuenta = new javax.swing.JTextField();
        BotonConsultaSaldo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        MostrarSaldo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ventana de Consulta de SAldo:");

        jLabel2.setText("Ingrese el Numero de Cuenta Para Consultar el Saldo:");

        BotonConsultaSaldo.setText("Consulta Saldo");
        BotonConsultaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaSaldoActionPerformed(evt);
            }
        });

        jLabel3.setText("Su saldo es:");

        MostrarSaldo.setText("0.0");

        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(MostrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(BotonConsultaSaldo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(CajaCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CajaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonConsultaSaldo)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MostrarSaldo))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Cancelar
		
		Inicio.menu_rp.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotonConsultaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaSaldoActionPerformed
        // Boton Consulta de Saldo
	Validaciones v = new Validaciones();
	String Cuenta=CajaCuenta.getText();
	Boolean esCorrecto=true;
	
	if(v.esNumero(Cuenta)){//----------------------------CUENTA
		//revisar que la cuenta Exista
			BaseDeDatos db = new BaseDeDatos();
			String consulta = "SELECT * FROM CUENTA WHERE ID_CUENTA="+Cuenta;
			Boolean banderaCuenta=false;
			try{
				Connection conn = db.conexion();
				if (conn != null) {
					Statement stmt = conn.createStatement();
					ResultSet rs = stmt.executeQuery(consulta);
					//datosCuenta=stmt.executeQuery(consulta);
					while(rs.next()){
						if(rs.getString("ID_CUENTA").equals(Cuenta)){
							banderaCuenta=true;
							break;
						}
					}
				} else {
						System.out.println("NO HAY CONEXION");
				}
				
				if(banderaCuenta){
					//Esta Bien La Cuenta
				}else{
					JOptionPane.showMessageDialog(null, "El Numero de Cuenta No Existe en la BD","ERROR",JOptionPane.ERROR_MESSAGE);
					esCorrecto=false;
				}
				
			}catch(Exception e){  
				JOptionPane.showMessageDialog(rootPane, "Numero de Cuenta Invalido No Existe Ese numero de Cuenta");
			}	 
	}else{
		JOptionPane.showMessageDialog(null, "La Cuenta debe ser Numerica","ERROR",JOptionPane.ERROR_MESSAGE);
		esCorrecto=false;
	}
	
	
	if(esCorrecto){
		JOptionPane.showMessageDialog(rootPane, "CORRECTO TRANSACCION");
		try{
			BaseDeDatos db1 = new BaseDeDatos();
			String consulta1 = "SELECT * FROM CUENTA WHERE ID_CUENTA="+Cuenta;
			Connection connn = db1.conexion();
			if (connn != null) {
				Statement stmt = connn.createStatement();
				datosCuenta= stmt.executeQuery(consulta1);
			}else{
				System.out.println("NO HAY CONEXION");
			}
			String saldo="0";
			while(datosCuenta.next()){
				saldo=datosCuenta.getString("SALDO");
			}
			
			this.MostrarSaldo.setText(saldo);
			
		}catch (SQLException e) {
			System.err.format("SQL Error : %s\n%s", e.getSQLState(), e.getMessage());
		}
	}
	
	
    }//GEN-LAST:event_BotonConsultaSaldoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ConsultaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ConsultaSaldo().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultaSaldo;
    private javax.swing.JTextField CajaCuenta;
    private javax.swing.JLabel MostrarSaldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
