/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1bases2;

import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Haldamir
 */
public class EstadoCuenta extends javax.swing.JFrame {

    public JFileChooser seleccionar = new JFileChooser();
    public File archivo;
    public FileOutputStream salida;
    public String escritorio = System.getProperty("user.home") + "\\Desktop\\";
    public EstadoCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No Cuenta");

        jButton1.setText("Generar Estado de Cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 209, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String reporte="<!DOCTYPE HTML5>\n" +
"<html>\n" +
"	<head>\n" +
"		<title>Reporte</title>\n" +
"		<meta charset=\"utf-8\">\n" +
"		<meta name=\"author\" content=\"\">\n" +
"		<meta name=\"description\" content=\"Ejercicios prácticos HTML5\">\n" +
"		<meta name=\"keywords\" content=\"Ejercicios, Soluciones, Prácticas, HTML5\">\n" +
"	</head>\n" +
"	<body>\n" +
"		\n" +
"		<h1><center>Reporte Senda de Auditoria</center></h1>\n" +
"		<center>\n" +
"			<table border=\"1\">\n" +
"			<tr>\n" +
"				<th bgcolor=\"yellow\">Fehca</th>\n" +
"				<th bgcolor=\"yellow\">Tipo de Transaccion</th>\n" +
"				<th bgcolor=\"yellow\">Saldo Inicial</th>\n" +
"				<th bgcolor=\"yellow\">Valor</th>\n" +
"				<th bgcolor=\"yellow\">Saldo Final</th>\n" +
"				<th bgcolor=\"yellow\">Id de La Agencia</th>\n" +
"				<th bgcolor=\"yellow\">Id del Usuario</th>\n" +
"			</tr>";	
        
        
        Validaciones v = new Validaciones();
        String cuenta = jTextField1.getText();
        //validaciones
        if(v.esNumero(cuenta)){
            //validar existencia
            Boolean existe = true;
            //validar existencia
            BaseDeDatos db = new BaseDeDatos();
            String consulta = "select * from cuenta where id_cuenta = "+cuenta;
            try{
                Connection conn = db.conexion();
                Statement stmt = conn.createStatement();
                ResultSet res = stmt.executeQuery(consulta);
                if(res.next() == false){
                    JOptionPane.showMessageDialog(null, "Esta cuenta no existe");
                    existe = false;
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error al consultar\nExcepcion: "+e,"ERROR", JOptionPane.ERROR_MESSAGE);
                existe = false;
            }
            
            if(existe){
                consulta = "select * from transaccion where id_cuenta = "+cuenta;
                db = new BaseDeDatos();
                try{
            Connection conn = db.conexion();
            if (conn != null) {
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery(consulta);
                    while(rs.next()){
			reporte+="<tr>\n" +
"				<td>"+rs.getString("FECHA")+"</td>\n" +
"				<td>"+rs.getString("TIPO_TRANSACCION")+"</td>\n" +
"				<td>"+rs.getString("SALDO_INICIAL")+"</td>\n" +
"				<td>"+rs.getString("VALOR")+"</td>\n" +
"				<td>"+rs.getString("SALDO_FINAL")+"</td>\n" +
"				<td>"+rs.getString("ID_AGENCIA")+"</td>\n" +
"				<td>"+rs.getString("ID_USUARIO")+"</td>\n" +
"			</tr>\n";
                    }
		reporte+="</table>\n" +
"		</center>\n" +
"	</body>\n" +
"</html>";
		
		GuardarComo(reporte);
		
            } else {
                    System.out.println("NO HAY CONEXION");
            }
        }catch(Exception e){  
            JOptionPane.showMessageDialog(null,"Error al llenar tabla de clientes\nClase: Principal -> 2721\nExcepcion: "+e,"ERROR", JOptionPane.ERROR_MESSAGE);
        }
                
                
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null, "La cuenta debe ser un campo numerico");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void GuardarComo(String documento){
        String txt=documento;
        seleccionar.setCurrentDirectory(new File(escritorio));
        if(seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.getName().endsWith(".html")){
                String Documento=txt;
                String mensaje=GuardarArchivo(archivo, Documento);
                if(mensaje!=null){
                    //JOptionPane.showMessageDialog(null, "::GUARDO::\n"+mensaje);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo no Compatible");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Error Extension");
            }
        }
    }
    

public String GuardarArchivo(File Archivo, String documento){
        String mensaje=null;
        try{
            salida=new FileOutputStream(Archivo);
            byte[] bytxt=documento.getBytes();
            salida.write(bytxt);
            mensaje="Archivo Guardado";
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo Guardar");
        }
        return documento;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
