/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1bases2;

/**
 *
 * @author carlosmonterroso
 */
public class MenuAdmin extends javax.swing.JFrame {

	/**
	 * Creates new form MenuAdmin
	 */
	public MenuAdmin() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonAbcBancos = new javax.swing.JButton();
        BotonAbcUsuarios = new javax.swing.JButton();
        BotonAbcAgencias = new javax.swing.JButton();
        BotonAbcMantenimientos = new javax.swing.JButton();
        BotonAbcApertura = new javax.swing.JButton();
        BotonAbcManejoCuentas = new javax.swing.JButton();
        BotonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu de Administrador:");

        BotonAbcBancos.setText("ABC Bancos");
        BotonAbcBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbcBancosActionPerformed(evt);
            }
        });

        BotonAbcUsuarios.setText("ABC Usuarios");
        BotonAbcUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAbcUsuariosActionPerformed(evt);
            }
        });

        BotonAbcAgencias.setText("ABC Agencias");

        BotonAbcMantenimientos.setText("Otros Mantenimientos");

        BotonAbcApertura.setText("Apertura de Cuenta");

        BotonAbcManejoCuentas.setText("Manejo de Cuentas");

        BotonCerrarSesion.setText("Cerrar Sesion");
        BotonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(BotonAbcBancos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAbcUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAbcAgencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAbcMantenimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(BotonAbcApertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonAbcManejoCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(BotonCerrarSesion)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(BotonCerrarSesion))
                .addGap(21, 21, 21)
                .addComponent(BotonAbcBancos)
                .addGap(18, 18, 18)
                .addComponent(BotonAbcUsuarios)
                .addGap(18, 18, 18)
                .addComponent(BotonAbcAgencias)
                .addGap(18, 18, 18)
                .addComponent(BotonAbcApertura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonAbcManejoCuentas)
                .addGap(30, 30, 30)
                .addComponent(BotonAbcMantenimientos)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAbcBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbcBancosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAbcBancosActionPerformed

    private void BotonAbcUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAbcUsuariosActionPerformed
        //Boton Abc Usuarios
		
		ABC_Usuario u=new ABC_Usuario();
		u.setLocationRelativeTo(null);
		u.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_BotonAbcUsuariosActionPerformed

    private void BotonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarSesionActionPerformed
        
		this.setVisible(false);
		Proyecto1Bases2.i.setVisible(true);
		Proyecto1Bases2.i.UserCaja.setText("");
		Proyecto1Bases2.i.PassCaja.setText("");
		
		
    }//GEN-LAST:event_BotonCerrarSesionActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuAdmin().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAbcAgencias;
    private javax.swing.JButton BotonAbcApertura;
    private javax.swing.JButton BotonAbcBancos;
    private javax.swing.JButton BotonAbcManejoCuentas;
    private javax.swing.JButton BotonAbcMantenimientos;
    private javax.swing.JButton BotonAbcUsuarios;
    private javax.swing.JButton BotonCerrarSesion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
